[package]
name = "linker-fix-3ds"
authors = [ "Andrea Ciliberti <meziu210@icloud.com>" ]
version = "0.1.0"
license = "MIT/Apache 2.0"
edition = "2018"

[dependencies]
ctru-sys = { git = "https://github.com/Meziu/ctru-rs.git" }
libc = { git = "https://github.com/Meziu/libc.git" }
